import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className='dark '>
      <body className={`${inter.className}  bg-slate-900 relative  m-0 pb-12 `}>
        <Providers>
          <NavBar />
          <main className='container h-full mt-12 p-8 min-h-screen mx-auto min-w-fill flex justify-center rounded-lg bg-slate-800 shadow-lg shadow-slate-700'>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
