import './globals.css'
import { Inter } from 'next/font/google'
import {Providers} from "./providers";
import NavBar from "@/components/NavBar";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <html lang="en" className='dark '>
      <body className={`${inter.className} bg-zinc-900`} >
        <Providers>
          <NavBar/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
